#!/bin/bash
# Startup-OS Folder Structure Generator
# Run: chmod +x create_startup_os.sh && ./create_startup_os.sh

ROOT="Startup-OS"
COUNT=0

mk() {
    mkdir -p "$1"
    touch "$1/.gitkeep"
    echo "  ✓ $1"
    ((COUNT++))
}

echo ""
echo "🚀 Startup-OS Folder Generator"
echo "📍 Location: $(pwd)"
echo "--------------------------------------------------"

# .claude
mk "$ROOT/.claude/System Prompts/Founder Prompts"
mk "$ROOT/.claude/System Prompts/Investor Prompts"
mk "$ROOT/.claude/System Prompts/Product Prompts"
mk "$ROOT/.claude/System Prompts/Strategy Prompts"
mk "$ROOT/.claude/System Prompts/Operations Prompts"
mk "$ROOT/.claude/Agents/Research Agent"
mk "$ROOT/.claude/Agents/Pitch Agent"
mk "$ROOT/.claude/Agents/Strategy Agent"
mk "$ROOT/.claude/Agents/Hiring Agent"
mk "$ROOT/.claude/Agents/Finance Agent"
mk "$ROOT/.claude/Workflows/Fundraising Workflow"
mk "$ROOT/.claude/Workflows/Hiring Workflow"
mk "$ROOT/.claude/Workflows/Product Launch Workflow"
mk "$ROOT/.claude/Workflows/Investor Update Workflow"
mk "$ROOT/.claude/Memory/Company Context"
mk "$ROOT/.claude/Memory/Founder Bios"
mk "$ROOT/.claude/Memory/Investor Profiles"
mk "$ROOT/.claude/Memory/Market Context"
mk "$ROOT/.claude/MCP Configs/CRM Connections"
mk "$ROOT/.claude/MCP Configs/Finance Integrations"
mk "$ROOT/.claude/MCP Configs/Collaboration Tools"

# Idea & Vision
mk "$ROOT/Idea & Vision/Problem Statement/Problem Discovery"
mk "$ROOT/Idea & Vision/Problem Statement/Pain Point Research"
mk "$ROOT/Idea & Vision/Problem Statement/Root Cause Analysis"
mk "$ROOT/Idea & Vision/Problem Statement/Problem Validation"
mk "$ROOT/Idea & Vision/Vision & Mission/Vision Statement"
mk "$ROOT/Idea & Vision/Vision & Mission/Mission Statement"
mk "$ROOT/Idea & Vision/Vision & Mission/Core Values"
mk "$ROOT/Idea & Vision/Vision & Mission/North Star"
mk "$ROOT/Idea & Vision/Vision & Mission/10 Year Vision"
mk "$ROOT/Idea & Vision/Opportunity Mapping/Market Gaps"
mk "$ROOT/Idea & Vision/Opportunity Mapping/Timing Analysis"
mk "$ROOT/Idea & Vision/Opportunity Mapping/Why Now"
mk "$ROOT/Idea & Vision/Opportunity Mapping/Unfair Advantage"
mk "$ROOT/Idea & Vision/Hypothesis/Core Assumptions"
mk "$ROOT/Idea & Vision/Hypothesis/Riskiest Assumptions"
mk "$ROOT/Idea & Vision/Hypothesis/Leap of Faith"
mk "$ROOT/Idea & Vision/Hypothesis/Validation Plan"
mk "$ROOT/Idea & Vision/Concept Development/Idea Iterations"
mk "$ROOT/Idea & Vision/Concept Development/Concept Notes"
mk "$ROOT/Idea & Vision/Concept Development/Brainstorm Sessions"
mk "$ROOT/Idea & Vision/Concept Development/Pivots & Decisions"
mk "$ROOT/Idea & Vision/AI Workflows/Problem Framer"
mk "$ROOT/Idea & Vision/AI Workflows/Opportunity Scorer"
mk "$ROOT/Idea & Vision/AI Workflows/Vision Statement Builder"

# Market Research
mk "$ROOT/Market Research/Market Sizing/TAM Analysis"
mk "$ROOT/Market Research/Market Sizing/SAM Analysis"
mk "$ROOT/Market Research/Market Sizing/SOM Analysis"
mk "$ROOT/Market Research/Market Sizing/Sizing Models"
mk "$ROOT/Market Research/Market Sizing/Market Maps"
mk "$ROOT/Market Research/Target Market/Segment Analysis"
mk "$ROOT/Market Research/Target Market/ICP Definition"
mk "$ROOT/Market Research/Target Market/Early Adopters"
mk "$ROOT/Market Research/Target Market/Beachhead Market"
mk "$ROOT/Market Research/Target Market/Expansion Markets"
mk "$ROOT/Market Research/Competitor Analysis/Direct Competitors"
mk "$ROOT/Market Research/Competitor Analysis/Indirect Competitors"
mk "$ROOT/Market Research/Competitor Analysis/Substitute Products"
mk "$ROOT/Market Research/Competitor Analysis/Competitive Matrix"
mk "$ROOT/Market Research/Competitor Analysis/Competitive Moat"
mk "$ROOT/Market Research/Industry Research/Industry Reports"
mk "$ROOT/Market Research/Industry Research/Trend Analysis"
mk "$ROOT/Market Research/Industry Research/Regulatory Landscape"
mk "$ROOT/Market Research/Industry Research/Technology Shifts"
mk "$ROOT/Market Research/Industry Research/Market Drivers"
mk "$ROOT/Market Research/Customer Research/Interview Notes"
mk "$ROOT/Market Research/Customer Research/Survey Results"
mk "$ROOT/Market Research/Customer Research/Behavioral Insights"
mk "$ROOT/Market Research/Customer Research/Jobs to Be Done"
mk "$ROOT/Market Research/Customer Research/Customer Quotes"
mk "$ROOT/Market Research/Geographic Research/Finland Market"
mk "$ROOT/Market Research/Geographic Research/West Africa Market"
mk "$ROOT/Market Research/Geographic Research/EU Market"
mk "$ROOT/Market Research/Geographic Research/Global Expansion"
mk "$ROOT/Market Research/AI Workflows/Market Sizer"
mk "$ROOT/Market Research/AI Workflows/Competitor Profiler"
mk "$ROOT/Market Research/AI Workflows/Research Synthesizer"

# Validation
mk "$ROOT/Validation/Customer Discovery/Interview Scripts"
mk "$ROOT/Validation/Customer Discovery/Interview Recordings"
mk "$ROOT/Validation/Customer Discovery/Discovery Notes"
mk "$ROOT/Validation/Customer Discovery/Pattern Analysis"
mk "$ROOT/Validation/Customer Discovery/Key Insights"
mk "$ROOT/Validation/MVP Testing/Smoke Tests"
mk "$ROOT/Validation/MVP Testing/Landing Page Tests"
mk "$ROOT/Validation/MVP Testing/Concierge MVP"
mk "$ROOT/Validation/MVP Testing/Wizard of Oz"
mk "$ROOT/Validation/MVP Testing/Prototype Tests"
mk "$ROOT/Validation/Demand Validation/Waitlist Data"
mk "$ROOT/Validation/Demand Validation/Pre Sales"
mk "$ROOT/Validation/Demand Validation/LOIs"
mk "$ROOT/Validation/Demand Validation/Pilot Agreements"
mk "$ROOT/Validation/Demand Validation/Conversion Evidence"
mk "$ROOT/Validation/Problem Validation/Pain Evidence"
mk "$ROOT/Validation/Problem Validation/Frequency Data"
mk "$ROOT/Validation/Problem Validation/Willingness to Pay"
mk "$ROOT/Validation/Problem Validation/Current Solutions"
mk "$ROOT/Validation/Solution Validation/Solution Demos"
mk "$ROOT/Validation/Solution Validation/Feedback Sessions"
mk "$ROOT/Validation/Solution Validation/Usability Tests"
mk "$ROOT/Validation/Solution Validation/Iteration Log"
mk "$ROOT/Validation/AI Workflows/Interview Analyzer"
mk "$ROOT/Validation/AI Workflows/Assumption Tester"
mk "$ROOT/Validation/AI Workflows/Validation Report Writer"

# Business Model
mk "$ROOT/Business Model/Business Model Canvas/Value Propositions"
mk "$ROOT/Business Model/Business Model Canvas/Customer Segments"
mk "$ROOT/Business Model/Business Model Canvas/Channels"
mk "$ROOT/Business Model/Business Model Canvas/Customer Relationships"
mk "$ROOT/Business Model/Business Model Canvas/Revenue Streams"
mk "$ROOT/Business Model/Business Model Canvas/Key Resources"
mk "$ROOT/Business Model/Business Model Canvas/Key Activities"
mk "$ROOT/Business Model/Business Model Canvas/Key Partnerships"
mk "$ROOT/Business Model/Business Model Canvas/Cost Structure"
mk "$ROOT/Business Model/Revenue Model/Pricing Strategy"
mk "$ROOT/Business Model/Revenue Model/Pricing Tiers"
mk "$ROOT/Business Model/Revenue Model/Monetization Plan"
mk "$ROOT/Business Model/Revenue Model/Revenue Experiments"
mk "$ROOT/Business Model/Revenue Model/Pricing Benchmarks"
mk "$ROOT/Business Model/Unit Economics/CAC Model"
mk "$ROOT/Business Model/Unit Economics/LTV Model"
mk "$ROOT/Business Model/Unit Economics/Payback Period"
mk "$ROOT/Business Model/Unit Economics/Gross Margin"
mk "$ROOT/Business Model/Unit Economics/Contribution Margin"
mk "$ROOT/Business Model/Value Proposition/Value Prop Canvas"
mk "$ROOT/Business Model/Value Proposition/Unique Differentiators"
mk "$ROOT/Business Model/Value Proposition/Messaging"
mk "$ROOT/Business Model/Value Proposition/Proof Points"
mk "$ROOT/Business Model/Go To Market/GTM Strategy"
mk "$ROOT/Business Model/Go To Market/Launch Sequence"
mk "$ROOT/Business Model/Go To Market/Channel Strategy"
mk "$ROOT/Business Model/Go To Market/Sales Motion"
mk "$ROOT/Business Model/Go To Market/Partnership Strategy"
mk "$ROOT/Business Model/AI Workflows/BMC Builder"
mk "$ROOT/Business Model/AI Workflows/Pricing Strategist"
mk "$ROOT/Business Model/AI Workflows/Unit Economics Calculator"

# Product
mk "$ROOT/Product/Product Strategy/Product Vision"
mk "$ROOT/Product/Product Strategy/Product Principles"
mk "$ROOT/Product/Product Strategy/Product Bets"
mk "$ROOT/Product/Product Strategy/Competitive Positioning"
mk "$ROOT/Product/Roadmap/Now"
mk "$ROOT/Product/Roadmap/Next"
mk "$ROOT/Product/Roadmap/Later"
mk "$ROOT/Product/Roadmap/Icebox"
mk "$ROOT/Product/Roadmap/Roadmap Archive"
mk "$ROOT/Product/MVP/MVP Scope"
mk "$ROOT/Product/MVP/MVP Design"
mk "$ROOT/Product/MVP/MVP Build"
mk "$ROOT/Product/MVP/MVP Metrics"
mk "$ROOT/Product/MVP/MVP Learnings"
mk "$ROOT/Product/Features/Feature Backlog"
mk "$ROOT/Product/Features/Feature Specs"
mk "$ROOT/Product/Features/In Development"
mk "$ROOT/Product/Features/Shipped Features"
mk "$ROOT/Product/Features/Killed Features"
mk "$ROOT/Product/Design/Wireframes"
mk "$ROOT/Product/Design/UI Designs"
mk "$ROOT/Product/Design/Prototypes"
mk "$ROOT/Product/Design/Design System"
mk "$ROOT/Product/Design/Brand Assets"
mk "$ROOT/Product/User Research/User Interviews"
mk "$ROOT/Product/User Research/Usability Tests"
mk "$ROOT/Product/User Research/User Feedback"
mk "$ROOT/Product/User Research/Analytics Insights"
mk "$ROOT/Product/User Research/Feature Requests"
mk "$ROOT/Product/Development/Tech Stack"
mk "$ROOT/Product/Development/Architecture Docs"
mk "$ROOT/Product/Development/Sprint Plans"
mk "$ROOT/Product/Development/Bug Reports"
mk "$ROOT/Product/Development/Release Notes"
mk "$ROOT/Product/Analytics/Product Metrics"
mk "$ROOT/Product/Analytics/Retention Data"
mk "$ROOT/Product/Analytics/Feature Adoption"
mk "$ROOT/Product/Analytics/Funnel Data"
mk "$ROOT/Product/Analytics/A-B Tests"
mk "$ROOT/Product/AI Workflows/PRD Generator"
mk "$ROOT/Product/AI Workflows/Feature Prioritizer"
mk "$ROOT/Product/AI Workflows/User Story Writer"

# Fundraising
mk "$ROOT/Fundraising/Fundraising Strategy/Funding Rounds Plan"
mk "$ROOT/Fundraising/Fundraising Strategy/Use of Funds"
mk "$ROOT/Fundraising/Fundraising Strategy/Funding Timeline"
mk "$ROOT/Fundraising/Fundraising Strategy/Round Structure"
mk "$ROOT/Fundraising/Fundraising Strategy/Dilution Planning"
mk "$ROOT/Fundraising/Pitch Materials/Pitch Decks"
mk "$ROOT/Fundraising/Pitch Materials/One Pagers"
mk "$ROOT/Fundraising/Pitch Materials/Executive Summary"
mk "$ROOT/Fundraising/Pitch Materials/Demo Videos"
mk "$ROOT/Fundraising/Pitch Materials/Pitch Deck Versions"
mk "$ROOT/Fundraising/Investor Pipeline/Target Investors"
mk "$ROOT/Fundraising/Investor Pipeline/Warm Intros"
mk "$ROOT/Fundraising/Investor Pipeline/Cold Outreach"
mk "$ROOT/Fundraising/Investor Pipeline/First Meetings"
mk "$ROOT/Fundraising/Investor Pipeline/Partner Meetings"
mk "$ROOT/Fundraising/Investor Pipeline/Term Sheet Stage"
mk "$ROOT/Fundraising/Investor Pipeline/Closed"
mk "$ROOT/Fundraising/Due Diligence/Data Room"
mk "$ROOT/Fundraising/Due Diligence/Financial Docs"
mk "$ROOT/Fundraising/Due Diligence/Legal Docs"
mk "$ROOT/Fundraising/Due Diligence/Technical Docs"
mk "$ROOT/Fundraising/Due Diligence/Team Docs"
mk "$ROOT/Fundraising/Due Diligence/Reference Checks"
mk "$ROOT/Fundraising/Term Sheets/Received Term Sheets"
mk "$ROOT/Fundraising/Term Sheets/Negotiation Notes"
mk "$ROOT/Fundraising/Term Sheets/Signed Term Sheets"
mk "$ROOT/Fundraising/Term Sheets/Declined Term Sheets"
mk "$ROOT/Fundraising/Cap Table/Current Cap Table"
mk "$ROOT/Fundraising/Cap Table/Option Pool"
mk "$ROOT/Fundraising/Cap Table/SAFE Notes"
mk "$ROOT/Fundraising/Cap Table/Convertible Notes"
mk "$ROOT/Fundraising/Cap Table/Pro Forma"
mk "$ROOT/Fundraising/Grants & Programs/Government Grants"
mk "$ROOT/Fundraising/Grants & Programs/EU Funding"
mk "$ROOT/Fundraising/Grants & Programs/Accelerator Programs"
mk "$ROOT/Fundraising/Grants & Programs/Competitions"
mk "$ROOT/Fundraising/Grants & Programs/Applications"
mk "$ROOT/Fundraising/Investor Relations/Investor Updates"
mk "$ROOT/Fundraising/Investor Relations/Board Meetings"
mk "$ROOT/Fundraising/Investor Relations/Board Decks"
mk "$ROOT/Fundraising/Investor Relations/Investor FAQs"
mk "$ROOT/Fundraising/Investor Relations/Communications Log"
mk "$ROOT/Fundraising/AI Workflows/Pitch Deck Builder"
mk "$ROOT/Fundraising/AI Workflows/Investor Researcher"
mk "$ROOT/Fundraising/AI Workflows/Investor Update Writer"

# Finance
mk "$ROOT/Finance/Financial Modeling/Revenue Models"
mk "$ROOT/Finance/Financial Modeling/Expense Models"
mk "$ROOT/Finance/Financial Modeling/Cash Flow Models"
mk "$ROOT/Finance/Financial Modeling/Scenario Models"
mk "$ROOT/Finance/Financial Modeling/Investor Models"
mk "$ROOT/Finance/Budgeting/Annual Budget"
mk "$ROOT/Finance/Budgeting/Monthly Budget"
mk "$ROOT/Finance/Budgeting/Department Budgets"
mk "$ROOT/Finance/Budgeting/Budget vs Actuals"
mk "$ROOT/Finance/Budgeting/Budget Reviews"
mk "$ROOT/Finance/Accounting/Chart of Accounts"
mk "$ROOT/Finance/Accounting/Invoices"
mk "$ROOT/Finance/Accounting/Receipts"
mk "$ROOT/Finance/Accounting/Payroll"
mk "$ROOT/Finance/Accounting/Monthly Close"
mk "$ROOT/Finance/Runway Management/Runway Calculator"
mk "$ROOT/Finance/Runway Management/Burn Rate Tracker"
mk "$ROOT/Finance/Runway Management/Cash Position"
mk "$ROOT/Finance/Runway Management/Extension Plans"
mk "$ROOT/Finance/Runway Management/Default Alive Model"
mk "$ROOT/Finance/Financial Reporting/P&L Statements"
mk "$ROOT/Finance/Financial Reporting/Balance Sheets"
mk "$ROOT/Finance/Financial Reporting/Cash Flow Statements"
mk "$ROOT/Finance/Financial Reporting/Board Financial Reports"
mk "$ROOT/Finance/Tax & Compliance/Tax Returns"
mk "$ROOT/Finance/Tax & Compliance/VAT-GST"
mk "$ROOT/Finance/Tax & Compliance/R&D Tax Credits"
mk "$ROOT/Finance/Tax & Compliance/Compliance Calendar"
mk "$ROOT/Finance/Banking/Bank Accounts"
mk "$ROOT/Finance/Banking/Transaction Records"
mk "$ROOT/Finance/Banking/Credit Lines"
mk "$ROOT/Finance/Banking/Multi Currency"
mk "$ROOT/Finance/AI Workflows/Runway Modeler"
mk "$ROOT/Finance/AI Workflows/Financial Forecast Builder"
mk "$ROOT/Finance/AI Workflows/Burn Rate Analyzer"

# Legal
mk "$ROOT/Legal/Company Formation/Incorporation Docs"
mk "$ROOT/Legal/Company Formation/Articles of Association"
mk "$ROOT/Legal/Company Formation/Shareholder Agreements"
mk "$ROOT/Legal/Company Formation/Operating Agreements"
mk "$ROOT/Legal/Company Formation/Registered Agents"
mk "$ROOT/Legal/IP & Trademarks/Trademark Filings"
mk "$ROOT/Legal/IP & Trademarks/Patent Applications"
mk "$ROOT/Legal/IP & Trademarks/Copyright Registrations"
mk "$ROOT/Legal/IP & Trademarks/IP Assignments"
mk "$ROOT/Legal/IP & Trademarks/Trade Secrets"
mk "$ROOT/Legal/Contracts/Customer Contracts"
mk "$ROOT/Legal/Contracts/Vendor Contracts"
mk "$ROOT/Legal/Contracts/Partner Agreements"
mk "$ROOT/Legal/Contracts/NDAs"
mk "$ROOT/Legal/Contracts/MoUs"
mk "$ROOT/Legal/Employment Law/Employment Contracts"
mk "$ROOT/Legal/Employment Law/Contractor Agreements"
mk "$ROOT/Legal/Employment Law/Equity Agreements"
mk "$ROOT/Legal/Employment Law/IP Assignment Agreements"
mk "$ROOT/Legal/Employment Law/Non Competes"
mk "$ROOT/Legal/Compliance/GDPR"
mk "$ROOT/Legal/Compliance/Data Privacy Policy"
mk "$ROOT/Legal/Compliance/Terms of Service"
mk "$ROOT/Legal/Compliance/Privacy Policy"
mk "$ROOT/Legal/Compliance/Cookie Policy"
mk "$ROOT/Legal/Regulatory/Licenses & Permits"
mk "$ROOT/Legal/Regulatory/Regulatory Filings"
mk "$ROOT/Legal/Regulatory/Industry Regulations"
mk "$ROOT/Legal/Regulatory/Cross Border Compliance"
mk "$ROOT/Legal/AI Workflows/Contract Summarizer"
mk "$ROOT/Legal/AI Workflows/Compliance Checker"
mk "$ROOT/Legal/AI Workflows/Legal Risk Flagging"

# Team & People
mk "$ROOT/Team & People/Founding Team/Founder Profiles"
mk "$ROOT/Team & People/Founding Team/Equity Split"
mk "$ROOT/Team & People/Founding Team/Roles & Responsibilities"
mk "$ROOT/Team & People/Founding Team/Founder Agreements"
mk "$ROOT/Team & People/Founding Team/Vesting Schedules"
mk "$ROOT/Team & People/Hiring/Hiring Plan"
mk "$ROOT/Team & People/Hiring/Job Descriptions"
mk "$ROOT/Team & People/Hiring/Candidate Pipeline"
mk "$ROOT/Team & People/Hiring/Interview Kits"
mk "$ROOT/Team & People/Hiring/Offer Letters"
mk "$ROOT/Team & People/Hiring/Hiring Decisions"
mk "$ROOT/Team & People/Onboarding/Onboarding Plans"
mk "$ROOT/Team & People/Onboarding/Day 1 Checklists"
mk "$ROOT/Team & People/Onboarding/Tool Access"
mk "$ROOT/Team & People/Onboarding/Culture Docs"
mk "$ROOT/Team & People/Onboarding/90 Day Plans"
mk "$ROOT/Team & People/Culture/Culture Deck"
mk "$ROOT/Team & People/Culture/Core Values"
mk "$ROOT/Team & People/Culture/Operating Principles"
mk "$ROOT/Team & People/Culture/Team Rituals"
mk "$ROOT/Team & People/Culture/Recognition Programs"
mk "$ROOT/Team & People/Performance/OKRs"
mk "$ROOT/Team & People/Performance/Performance Reviews"
mk "$ROOT/Team & People/Performance/1-1 Templates"
mk "$ROOT/Team & People/Performance/Feedback Framework"
mk "$ROOT/Team & People/Performance/PIP Process"
mk "$ROOT/Team & People/Advisors/Advisor Profiles"
mk "$ROOT/Team & People/Advisors/Advisor Agreements"
mk "$ROOT/Team & People/Advisors/Advisor Equity"
mk "$ROOT/Team & People/Advisors/Engagement Plans"
mk "$ROOT/Team & People/Advisors/Meeting Notes"
mk "$ROOT/Team & People/Org Structure/Org Charts"
mk "$ROOT/Team & People/Org Structure/Team Structure"
mk "$ROOT/Team & People/Org Structure/Reporting Lines"
mk "$ROOT/Team & People/Org Structure/Future Org Design"
mk "$ROOT/Team & People/AI Workflows/JD Generator"
mk "$ROOT/Team & People/AI Workflows/Culture Doc Builder"
mk "$ROOT/Team & People/AI Workflows/Hiring Scorecard Builder"

# Operations
mk "$ROOT/Operations/Company Handbook/Mission & Values"
mk "$ROOT/Operations/Company Handbook/Policies"
mk "$ROOT/Operations/Company Handbook/Benefits"
mk "$ROOT/Operations/Company Handbook/Work Guidelines"
mk "$ROOT/Operations/Company Handbook/Handbook Updates"
mk "$ROOT/Operations/SOPs/Core Processes"
mk "$ROOT/Operations/SOPs/Department SOPs"
mk "$ROOT/Operations/SOPs/Emergency Procedures"
mk "$ROOT/Operations/SOPs/Runbooks"
mk "$ROOT/Operations/Tools & Stack/Software Inventory"
mk "$ROOT/Operations/Tools & Stack/Access Management"
mk "$ROOT/Operations/Tools & Stack/Vendor List"
mk "$ROOT/Operations/Tools & Stack/SaaS Subscriptions"
mk "$ROOT/Operations/Tools & Stack/IT Setup Guides"
mk "$ROOT/Operations/Meetings/All Hands"
mk "$ROOT/Operations/Meetings/Team Standups"
mk "$ROOT/Operations/Meetings/Leadership Meetings"
mk "$ROOT/Operations/Meetings/Board Meetings"
mk "$ROOT/Operations/Meetings/Decisions Log"
mk "$ROOT/Operations/Project Management/Active Projects"
mk "$ROOT/Operations/Project Management/Project Templates"
mk "$ROOT/Operations/Project Management/Milestones"
mk "$ROOT/Operations/Project Management/Dependencies"
mk "$ROOT/Operations/Project Management/Completed Projects"
mk "$ROOT/Operations/Remote Operations/Remote Policy"
mk "$ROOT/Operations/Remote Operations/Async Guidelines"
mk "$ROOT/Operations/Remote Operations/Time Zone Management"
mk "$ROOT/Operations/Remote Operations/Virtual Offsites"
mk "$ROOT/Operations/AI Workflows/Meeting Summarizer"
mk "$ROOT/Operations/AI Workflows/SOP Generator"
mk "$ROOT/Operations/AI Workflows/Process Optimizer"

# Go To Market
mk "$ROOT/Go To Market/Launch Strategy/Pre Launch"
mk "$ROOT/Go To Market/Launch Strategy/Launch Week"
mk "$ROOT/Go To Market/Launch Strategy/Post Launch"
mk "$ROOT/Go To Market/Launch Strategy/Launch Checklist"
mk "$ROOT/Go To Market/Launch Strategy/Launch Retrospective"
mk "$ROOT/Go To Market/Positioning/Positioning Statement"
mk "$ROOT/Go To Market/Positioning/Messaging Framework"
mk "$ROOT/Go To Market/Positioning/Tagline Options"
mk "$ROOT/Go To Market/Positioning/Value Prop Testing"
mk "$ROOT/Go To Market/Sales Motion/Sales Playbook"
mk "$ROOT/Go To Market/Sales Motion/Sales Scripts"
mk "$ROOT/Go To Market/Sales Motion/Demo Flow"
mk "$ROOT/Go To Market/Sales Motion/Objection Handling"
mk "$ROOT/Go To Market/Sales Motion/Pricing Conversations"
mk "$ROOT/Go To Market/Early Customers/Design Partners"
mk "$ROOT/Go To Market/Early Customers/Pilot Customers"
mk "$ROOT/Go To Market/Early Customers/Logo Customers"
mk "$ROOT/Go To Market/Early Customers/Case Studies"
mk "$ROOT/Go To Market/Early Customers/Testimonials"
mk "$ROOT/Go To Market/Distribution/Channel Strategy"
mk "$ROOT/Go To Market/Distribution/Product Hunt"
mk "$ROOT/Go To Market/Distribution/Directories"
mk "$ROOT/Go To Market/Distribution/Communities"
mk "$ROOT/Go To Market/Distribution/Marketplaces"
mk "$ROOT/Go To Market/PR & Comms/Press Releases"
mk "$ROOT/Go To Market/PR & Comms/Media Kit"
mk "$ROOT/Go To Market/PR & Comms/Journalist Outreach"
mk "$ROOT/Go To Market/PR & Comms/Press Coverage"
mk "$ROOT/Go To Market/PR & Comms/Crisis Comms"
mk "$ROOT/Go To Market/AI Workflows/Launch Plan Builder"
mk "$ROOT/Go To Market/AI Workflows/Positioning Advisor"
mk "$ROOT/Go To Market/AI Workflows/Press Release Writer"

# Customers
mk "$ROOT/Customers/Customer Success/Onboarding Flows"
mk "$ROOT/Customers/Customer Success/Success Plans"
mk "$ROOT/Customers/Customer Success/QBR Templates"
mk "$ROOT/Customers/Customer Success/Health Scores"
mk "$ROOT/Customers/Customer Success/Expansion Plays"
mk "$ROOT/Customers/Support/Support Playbooks"
mk "$ROOT/Customers/Support/FAQ Library"
mk "$ROOT/Customers/Support/Ticket Templates"
mk "$ROOT/Customers/Support/Escalation Matrix"
mk "$ROOT/Customers/Support/Support Metrics"
mk "$ROOT/Customers/Feedback/Feature Requests"
mk "$ROOT/Customers/Feedback/Bug Reports"
mk "$ROOT/Customers/Feedback/NPS Data"
mk "$ROOT/Customers/Feedback/CSAT Scores"
mk "$ROOT/Customers/Feedback/Feedback Themes"
mk "$ROOT/Customers/Retention/Churn Analysis"
mk "$ROOT/Customers/Retention/Save Plays"
mk "$ROOT/Customers/Retention/Win Back Campaigns"
mk "$ROOT/Customers/Retention/Retention Experiments"
mk "$ROOT/Customers/Referrals/Referral Program"
mk "$ROOT/Customers/Referrals/Advocate List"
mk "$ROOT/Customers/Referrals/Referral Tracking"
mk "$ROOT/Customers/Referrals/Incentive Structure"
mk "$ROOT/Customers/AI Workflows/Churn Predictor"
mk "$ROOT/Customers/AI Workflows/CS Playbook Builder"
mk "$ROOT/Customers/AI Workflows/Feedback Analyzer"

# Growth & Marketing
mk "$ROOT/Growth & Marketing/Growth Strategy/AARRR Framework"
mk "$ROOT/Growth & Marketing/Growth Strategy/Growth Model"
mk "$ROOT/Growth & Marketing/Growth Strategy/North Star Metric"
mk "$ROOT/Growth & Marketing/Growth Strategy/Growth Experiments"
mk "$ROOT/Growth & Marketing/Growth Strategy/Growth Reviews"
mk "$ROOT/Growth & Marketing/Content/Blog"
mk "$ROOT/Growth & Marketing/Content/Social Media"
mk "$ROOT/Growth & Marketing/Content/Video"
mk "$ROOT/Growth & Marketing/Content/Newsletters"
mk "$ROOT/Growth & Marketing/Content/Content Calendar"
mk "$ROOT/Growth & Marketing/SEO/Keyword Research"
mk "$ROOT/Growth & Marketing/SEO/Content SEO"
mk "$ROOT/Growth & Marketing/SEO/Technical SEO"
mk "$ROOT/Growth & Marketing/SEO/Link Building"
mk "$ROOT/Growth & Marketing/Paid Growth/Google Ads"
mk "$ROOT/Growth & Marketing/Paid Growth/Meta Ads"
mk "$ROOT/Growth & Marketing/Paid Growth/LinkedIn Ads"
mk "$ROOT/Growth & Marketing/Paid Growth/Ad Creative"
mk "$ROOT/Growth & Marketing/Community/Community Strategy"
mk "$ROOT/Growth & Marketing/Community/Platform Setup"
mk "$ROOT/Growth & Marketing/Community/Ambassador Program"
mk "$ROOT/Growth & Marketing/Community/Engagement Tactics"
mk "$ROOT/Growth & Marketing/AI Workflows/Growth Experiment Designer"
mk "$ROOT/Growth & Marketing/AI Workflows/Content Generator"
mk "$ROOT/Growth & Marketing/AI Workflows/Channel Optimizer"

# Partnerships & Ecosystem
mk "$ROOT/Partnerships & Ecosystem/Strategic Partnerships/Partner Strategy"
mk "$ROOT/Partnerships & Ecosystem/Strategic Partnerships/Partner Pipeline"
mk "$ROOT/Partnerships & Ecosystem/Strategic Partnerships/Partner Agreements"
mk "$ROOT/Partnerships & Ecosystem/Strategic Partnerships/Partner Reviews"
mk "$ROOT/Partnerships & Ecosystem/Accelerators & Incubators/Applications"
mk "$ROOT/Partnerships & Ecosystem/Accelerators & Incubators/Active Programs"
mk "$ROOT/Partnerships & Ecosystem/Accelerators & Incubators/Alumni Network"
mk "$ROOT/Partnerships & Ecosystem/Accelerators & Incubators/Program Benefits"
mk "$ROOT/Partnerships & Ecosystem/Ecosystem/Tech Partners"
mk "$ROOT/Partnerships & Ecosystem/Ecosystem/Integration Partners"
mk "$ROOT/Partnerships & Ecosystem/Ecosystem/Distribution Partners"
mk "$ROOT/Partnerships & Ecosystem/Ecosystem/Community Partners"
mk "$ROOT/Partnerships & Ecosystem/Mentors & Network/Mentor List"
mk "$ROOT/Partnerships & Ecosystem/Mentors & Network/Intro Requests"
mk "$ROOT/Partnerships & Ecosystem/Mentors & Network/Network Map"
mk "$ROOT/Partnerships & Ecosystem/Mentors & Network/Coffee Chats Log"
mk "$ROOT/Partnerships & Ecosystem/AI Workflows/Partner Researcher"
mk "$ROOT/Partnerships & Ecosystem/AI Workflows/Intro Email Writer"
mk "$ROOT/Partnerships & Ecosystem/AI Workflows/Partnership Deal Builder"

# Analytics & Metrics
mk "$ROOT/Analytics & Metrics/North Star Metric/NSM Definition"
mk "$ROOT/Analytics & Metrics/North Star Metric/NSM Tracking"
mk "$ROOT/Analytics & Metrics/North Star Metric/Input Metrics"
mk "$ROOT/Analytics & Metrics/North Star Metric/NSM Reviews"
mk "$ROOT/Analytics & Metrics/Startup Metrics/MRR ARR"
mk "$ROOT/Analytics & Metrics/Startup Metrics/Growth Rate"
mk "$ROOT/Analytics & Metrics/Startup Metrics/Churn Rate"
mk "$ROOT/Analytics & Metrics/Startup Metrics/NPS"
mk "$ROOT/Analytics & Metrics/Startup Metrics/DAU MAU"
mk "$ROOT/Analytics & Metrics/Startup Metrics/Activation Rate"
mk "$ROOT/Analytics & Metrics/Investor Metrics/Monthly Metrics"
mk "$ROOT/Analytics & Metrics/Investor Metrics/Board Metrics"
mk "$ROOT/Analytics & Metrics/Investor Metrics/Cohort Data"
mk "$ROOT/Analytics & Metrics/Investor Metrics/Benchmark Comparisons"
mk "$ROOT/Analytics & Metrics/Dashboards/Founder Dashboard"
mk "$ROOT/Analytics & Metrics/Dashboards/Investor Dashboard"
mk "$ROOT/Analytics & Metrics/Dashboards/Product Dashboard"
mk "$ROOT/Analytics & Metrics/Dashboards/Growth Dashboard"
mk "$ROOT/Analytics & Metrics/AI Workflows/Metrics Narrator"
mk "$ROOT/Analytics & Metrics/AI Workflows/Investor Update Builder"
mk "$ROOT/Analytics & Metrics/AI Workflows/Growth Diagnoser"

# Knowledge & Learning
mk "$ROOT/Knowledge & Learning/Founder Learning/Book Notes"
mk "$ROOT/Knowledge & Learning/Founder Learning/Course Notes"
mk "$ROOT/Knowledge & Learning/Founder Learning/Conference Notes"
mk "$ROOT/Knowledge & Learning/Founder Learning/Podcast Notes"
mk "$ROOT/Knowledge & Learning/Startup Playbooks/YC Playbooks"
mk "$ROOT/Knowledge & Learning/Startup Playbooks/a16z Resources"
mk "$ROOT/Knowledge & Learning/Startup Playbooks/First Round Resources"
mk "$ROOT/Knowledge & Learning/Startup Playbooks/Custom Playbooks"
mk "$ROOT/Knowledge & Learning/Lessons Learned/Monthly Reflections"
mk "$ROOT/Knowledge & Learning/Lessons Learned/Failure Analysis"
mk "$ROOT/Knowledge & Learning/Lessons Learned/Pivot History"
mk "$ROOT/Knowledge & Learning/Lessons Learned/Decision Journal"
mk "$ROOT/Knowledge & Learning/Research Library/Market Research"
mk "$ROOT/Knowledge & Learning/Research Library/Competitor Research"
mk "$ROOT/Knowledge & Learning/Research Library/Technology Research"
mk "$ROOT/Knowledge & Learning/Research Library/Academic Papers"
mk "$ROOT/Knowledge & Learning/AI Workflows/Learning Summarizer"
mk "$ROOT/Knowledge & Learning/AI Workflows/Decision Journal Assistant"
mk "$ROOT/Knowledge & Learning/AI Workflows/Research Curator"

# Archive
mk "$ROOT/Archive/Old Pitch Decks"
mk "$ROOT/Archive/Rejected Ideas"
mk "$ROOT/Archive/Pivots History"
mk "$ROOT/Archive/Closed Deals"
mk "$ROOT/Archive/Past Experiments"

echo "--------------------------------------------------"
echo "✅ Done! $COUNT folders created."
echo "📂 Open: $(pwd)/$ROOT"
echo ""
